# In-Class Programming Activity, Day 9
## Meghan Roffler
Your work goes here ...

#The Deck of Cards
```{r}
poker_deck <- c(outer((10 * 2:14), 1:4, '+'))
```

#Calculating Suits and Ranks
```{r}
ranks <- function(deck) {
  deck %/% 10
}
suits <- function(deck) {
  deck %% 10
}
```

#Three of a Kind
```{r}
is_three_of_a_kind <- function(fiveCardHand){
  lengths(table(suits(fiveCardHand))) == 3
  max(table(ranks(fiveCardHand))) == 3
}
```

#Straight Flush
```{r}
is_straight_flush <- function(fiveCardHand){
  is_flush(fiveCardHand) && is_straight(fiveCardHand)
}
```

#Two Pair
```{r}
is_two_pair <- function(fiveCardHand){
  sum(table(ranks(fiveCardHand)) == 2) == 2
}
```

#Pair
```{r}
is_pair <- function(fiveCardHand){
  length(table(ranks(fiveCardHand))) == 4
}
```

#Royal Flush
```{r}
is_royal_flush <- function(fiveCardHand){
  is_straight_flush(fiveCardHand) && max(rank(fiveCardHand) == 14)
  }
```

#Four of a Kind
```{r}
is_four_of_a_kind <- function(fiveCardHand){
  max(table(ranks(fiveCardHand))) == 4
}
```

#Full House
```{r}
is_full_house <- function(fiveCardHand){
  is_three_of_a_kind(fiveCardHand) && (length(table(ranks(fiveCardHand))) == 2)
}
```

#Flush
```{r}
is_flush <- function(fiveCardHand){ 
  max(table(suits(fiveCardHand))) == 5
  }
```

#Straight
```{r}
is_straight <- function(fiveCardHand) {
  all(diff(sort(ranks(fiveCardHand))) == 1)
}
```

#Test Hand
```{r}
test_hand_1 <- function(poker_deck){
  sample(poker_deck, 5)
}

test_hand_2 <- function(poker_deck){
 sample(poker_deck, 5)
}

is_royal_flush(test_hand_1(poker_deck))
is_full_house(test_hand_2(poker_deck))
```

#Estimating Probabilities
```{r}
before_draw <- function(...) {
  five_cards <- sample(poker_deck, 5)
  if (is_royal_flush(five_cards)) {
    return("royal flush")
  } else if (is_straight_flush(five_cards)) {
    return("straight flush")
  } else if (is_four_of_a_kind(five_cards)) {
    return("four of a kind")
  } else if (is_full_house(five_cards)) {
    return("full house")
  } else if (is_straight(five_cards)) {
    return("straight")
  } else if (is_three_of_a_kind(five_cards)) {
    return("three of a kind")
  } else if (is_two_pair(five_cards)) {
    return("two pair")
  } else if (is_pair(five_cards)) {
    return("pair")
  } else {
    return("None")
  }
}

table(sapply(1:10000, FUN=before_draw))
```


## Test statements

```{r}
scoreActivity::score253(9)
```